tools:
  - class_name: "recipe.chartool.chartool.CustomSandboxFusionTool"
    config:
      sandbox_fusion_url: "http://sandbox_fusion_url"
      num_workers: 256
      enable_global_rate_limit: true
      rate_limit: 256
      default_timeout: 30
      default_language: "python"
      memory_limit_mb: 1024
      type: native

    tool_schema:
      type: "function"
      function:
        name: "python_interpreter"
        description: "Execute Python code to analyze chart images."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The python code to execute."
          required: ["code"]
